baseurl = "https://cyris.pen.moe/"
languageCode = "en-us"
Title = "Cyris's pen"
theme = "hugo-theme-yuki"
publishDir = "docs"

# Copyright notice. This will display on the footer.
copyright = ""
 
# Theme config
[params]
  paginate = 10
  
  # The information will display on the post pages.
  author = "Cyris"
  description = "Web Developer"
  authorwebsite = "https://cyris.moe"
  
  # The path to your images
  favicon = "https://cdn.jsdelivr.net/npm/cyris@1.0.1/favicon.png"
  logo = "https://cdn.jsdelivr.net/npm/cyris@1.0.1/favicon.png"
  avatar = "/images/profile.png"
  displayImg = "/images/display.png"
  
  # This will display on the index page
  snsTitle = "Cyris's pen"
  
  # Google Analytics API key.
  ga_api_key = "UA-120896908-1"
  
# Navbar config
[[menu.nav]]
    name = "HOME"
    url = "/"
    weight = 1

[[menu.nav]]
    name = "BLOG"
    url = "/posts"
    weight = 2

[[menu.nav]]
    name = "ABOUT"
    url = "/pages/about"
    weight = 3
    
[[menu.nav]]
    name = "TAGS"
    url = "/tags/"
    weight = 4
    
[[menu.nav]]
    name = "FRIENDS"
    url = "/pages/links"
    weight = 5

# Social accounts config (This will display on the index page)
[[menu.social]]
    name = "CYRIS.MOE"
    url = "https://cyris.moe"
    weight = 1
    
[[menu.social]]
    name = "Twitter"
    url = "https://twitter.com/cyris_moe"
    weight = 2

[[menu.social]]
    name = "GitHub"
    url = "https://github.com/iCyris"
    weight = 3

