theme: ume

siteConfig:
  title: "Cyris's Pen"
  description: "Cyris's blog"
  url: "https://cyris.moe"
  author: "Cyris"
  email: "cyris@pen.moe"

themeConfig:
  title: "Cyris's Pen"
  subTitle: "像猫一样充满好奇"
  copyRight: "© Cyris's Pen"
  sideBar:
    - title: "About"
      link: "/about.html"
    - title: "Friends"
      link: "/friends.html"

  # The Home section on sidebar (mobile)
  spHome:
      title: "Home"
      link: "/"

markdown:
  highlighter: "prism"

plugins:
  - resolve: saber-plugin-query-posts
  - resolve: saber-plugin-generate-feed
  - resolve: "saber-plugin-google-analytics"
    options: 
      trackId: "UA-120896908-1"
